[package]
name = "leetcode"
version = "0.1.0"
authors = ["Jochen Hinrichsen <jochen.hinrichsen@kambrium.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
